# Generated by Django 4.0.3 on 2022-04-20 07:35

from django.db import migrations, models
import gdstorage.storage
import music_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('music_upload', '0003_remove_music_id_alter_music_file_alter_music_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='music/', validators=[music_upload.models.validate_file_extension]),
        ),
    ]
